apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::703705871361:user/github-ci-simplebank
      username: github-ci
      groups:
        - system:masters
